### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by rhenley** [PacificBiosciences/blasr#196]
Hello, I'm very much a begginer when it comes to installing these sorts of programs so apologize if this is a basic question, but when I run the make command I get the following error and I'm not quite sure how to resolve it
```
-o blasr -O3 -g -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/Users/Henley/blasr/libcpp/alignment -I/Users/Henley/blasr/libcpp/hdf -I/Users/Henley/blasr/libcpp/pbdata  -MF"blasr.d" Blasr.o -static -L/Users/Henley/blasr/libcpp/alignment -L/Users/Henley/blasr/libcpp/hdf -L/Users/Henley/blasr/libcpp/pbdata -lpbihdf -lblasr -lpbihdf -lpbdata -lpbbam -lhdf5_cpp -lhdf5 -lhts  -lz  -lpthread -ldl
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [blasr] Error 1
```

**Comment by pb-cdunn** [comment]
Your problem is `-static`, as described [here](http://lists.apple.com/archives/unix-porting/2004/Oct/msg00015.html).

You need to run `configure.py` with `--shared`. See `travis.sh` for an example, or try to follow [our installation guide](https://github.com/PacificBiosciences/blasr/blob/master/README.INSTALL.md).

**Comment by rhenley** [comment]
Thanks for your help, but now I'm getting this error 

ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
