### ISSUE TITLE
Installing bax2bam

### ISSUE THREAD

**Issue by nickjhathaway** [PacificBiosciences/blasr#224]
Is there an easy way to install bax2bam?  I need it to run pbccs on data I had to download form SRA (https://www.ncbi.nlm.nih.gov/sra?term=SRP051686).  I managed to get it to build by changing several parameters in the makefile and Cmake files in the bax2bam folder (had to turn off gtest i couldn't locate it) and had to change the location where it looked for pbbam.  I also had to create some symlinks to libraries (for libblasr  libpbihdf ibpbdata libhdf5_cpp libhdf5, the makefile wasn't looking for the .so extension for build rules and was failing).  I finally got it to build but it doesn't work consistently, I get the following error on all by one set of .bax.h5 files.

ERROR: BindingKit, SequencingKit, and ChangeListID are mandatory but unavailable

I'm not sure if this is due to the way I had to get bam2bax to build or if I'm just missing more libraries.  Any help would be appreciated

Thanks!

**Comment by evolvedmicrobe** [comment]
+1

**Comment by pb-cdunn** [comment]
@evolvedmicrobe, a new feature of GitHub lets you "+1" a comment directly.

@nickjhathaway, short answer: Try pitchfork.
* https://github.com/PacificBiosciences/pitchfork

I try to discourage PB devs from spending much time on individual integration problems because every system is different. Pitchfork works, which suffices to prove that the bug is not ours, but you are also free to design your own integration system, or to write adapters for an existing system (e.g. homebrew, yum, easyinstall, spack, etc.).

**Comment by mhsieh** [comment]
@nickjhathaway let me know if you need help.
