### ISSUE TITLE
Clean up blasr options, switch to POSIX parsing with GNU long extentions

### ISSUE THREAD

**Issue by pbjd** [PacificBiosciences/blasr#229]
SMRTAnalysis tools are now all adopting this convention.  http://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

This is a simple change in BLASR, but may have a significant blast radius in workflows that use it (e.g., pbalign).  

We also want to deprecate redundant and ancient options (e.g., --placeRepeatsRandom, --minAln, --minAlign, --minLength, etc)

**Comment by pb-cdunn** [comment]
I have always liked that POSIX standard, as it reduces the need to touch the SHIFT key, a blessing for my delicate pinky fingers.

>  Option names are typically one to three words long, **with hyphens to separate words**.

I.e. `--min-aln` instead of `--minAln` or `--min_aln`.

I don't suggest changing these now. But in new projects, it's a good idea to follow POSIX.

Vlad, here is a GitHub trick for you: If you include the string `#229` in a blasr commit-message related to this Issue, then this issue will automatically have a note pointing to that commit. And when someone views that commit in GitHub, they can click on 229 to see what Issue it was meant to address. E.g.
* #229

If the Issue is in a different repo, then you would need a longer string, like this: `PacificBiosciences/blasr#229`. E.g.
* PacificBiosciences/blasr#229

You can click on the "pencil" icon above my comment to see the raw markdown. For more details, see GitHub-flavored markdown docs here:
* https://guides.github.com/features/mastering-markdown/
* https://help.github.com/articles/autolinked-references-and-urls/

**Comment by wangyugui** [comment]
--sam is no longer supported in blasr 5.2, but --bam is not a valid option.

# blasr --version
blasr   5.2.3194382

# blasr /nfs/bio-doc/RNA-seq/rRNA/RNA5S1.fa /usr/bio-ref/GRCh38.p7/GRCh38.dna.fa --sa /usr/bio-ref/GRCh38.p7/GRCh38.dna.fa.s
a --bam --out blasr.bam --printSAMQV --cigarUseSeqMatch --nproc 48 --hitPolicy allbest --bestn 20 --nCandidates 20
ERROR: -bam is not a valid option.
