### ISSUE TITLE
ERROR: bam is not a valid option.

### ISSUE THREAD

**Issue by bananabenana** [PacificBiosciences/blasr#253]
Hey guys, I'm having a bit of trouble running blasr.

blasr can be called, and the  --help output gives me the format:

`blasr reads.bam genome.fasta --bam --out out.bam
`
When I input my files: 

- .bam generated by bax2bam

- reference_genome.fa

it gives me:

> ERROR: -bam is not a valid option.

If I remove --bam option:

> [INFO] 2016-06-15T02:33:18 [blasr] started.
> ERROR! Hit unreachable code in files/ReaderAgglomerate.cpp:293
> blasr: files/ReaderAgglomerate.cpp:293: int ReaderAgglomerate::Initialize(bool): Assertion `0' failed.
> zsh: abort      ./blasr  reference_genome.fa --out 

What's my fix here?

Thanks

**Comment by vrainish-pacbio** [comment]
Hi,
 
Make sure your blasr  supports bam,
You need to clone and use pitchfork to build it.
please, see pitchfork for instructions how to build it , then try to reissue your command

https://github.com/PacificBiosciences/pitchfork

If the problem persist, just comment here. Please, issue command 

blasr --version 

and attach the output to your comment.

**Comment by bananabenana** [comment]
Hey,

I did install pitchfork

`blasr --version
`

> blasr	5.2.badc092


I didn't mention this because I forgot, but when I try to call blasr, it gives me this message:

> ./blasr: error while loading shared libraries: libpbihdf.so: cannot open shared object file: No such file or directory

in order for blasr to work, I have to run:
`export LD_LIBRARY_PATH=/home/manager/Downloads/blasr/libcpp/alignment:/home/manager/Downloads/blasr/libcpp/hdf:/home/manager/Downloads/blasr/libcpp/pbdata:/usr/local/hdf5/lib::::`
every time.


I assume I went wrong in the installation somewhere.

**Comment by vrainish-pacbio** [comment]
It's great that your problem has been resolved.

Indeed, you need to export LD_LIBRARY_PATH for Blasr to work, after you build it

This step (exporting LD_LIBRARY_PATH) is emphasized in "step by step blasr installation example" on blasr wiki page which describes how to build stand-alone blasr WITHOUT bam support ( building stand-alone Blasr WITH bam support is more complicated and requires cloning and building few additional libraries beyond blasr and pbbam, that's why we recommend pitchfork for this purpose).

We'll make sure that exporting LD_LIBRARY_PATH step is clearly mentioned in pitchfork wiki/doc as well to avoid misunderstanding.
