### ISSUE TITLE
blasr command not found

### ISSUE THREAD

**Issue by mimita3635** [PacificBiosciences/blasr#323]
I was trying to run the blasr -h command after successful installation. But I could not find the alignment/bin/blasr folder. Will anyone please provide a detailed explanation on how to run blasr? 

Thanking in advance :)

**Comment by mjhsieh** [comment]
Can you tell us which installation recipe did you follow to install blasr?

**Comment by mjhsieh** [comment]
It depends on where you current directory is, if blasr is not in your PATH variable, you need to specify the full path.

**Comment by mimita3635** [comment]
https://github.com/PacificBiosciences/blasr/wiki/step-by-step-blasr-installation-example

I followed the instructions on this link for Blasr installation. But I did not understand the command export LD_LIBRARY_PATH. Where should I export it and how? can you please help me out with that?

**Comment by mjhsieh** [comment]
This is a bash command to let the environment variable specified in current shell to be passed to the program you run under this shell. It's nice that you got the installation going, but I think you need to find somebody who knows unix to help you or start to learn linux really really fast, because you are going to need it.

**Comment by mimita3635** [comment]
I performed a fresh installation of Blasr and now it's running just fine. Thanks anyway
