### ISSUE TITLE
How much memory will be used?

### ISSUE THREAD

**Issue by zhk2017** [PacificBiosciences/blasr#336]
reads.fasta: 80G bases
genome.fasta: 550M bases
-nproc 36

when i use above data do alignment, how much memory will be used? Is there any formula could be used calculate it?

At present,  resource consumption as below: 
 PID     USER       PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  DATA COMMAND                                                                      
22779 litt   20   0  312g 200g  63m S 3436.5 90.9  29230:17  236g

**Comment by alwaysrejoice** [comment]
Hi, I also have same question.
I am running blasr with
reads.fastq 420 Gb
genome.fasta 3Gb
-nproc 24
 How many threads should I use to run this data in order to optimize the efficiency?

**Comment by ylipacbio** [comment]
I would recommend you first chunk reads.fastq into several pieces and launch several blasr jobs on multiple computing nodes (e.g., SGE) or if you don't have SGE, run them sequentially.
* you may get some intuition w.r.t. runtime memory consumption by running blasr on one piece of FASTA/FASTQ file.
* it prevents loosing all output alignments if anything happen during the long run.
* using multiple  nodes is much faster 

The memory consumption depends on average read lengths, repetitiveness and size of reference genome, blasr parameters. Typical resequcing job using the default parameters aligning pacbio raw reads to human genome, with --nproc 10 usually takes somewhere between 20G ~ 30G memory.

236G memory consumption looks fishy. 

Note that if you are aligning long reads (e.g., contigs or chromosomes) to reference genome, running blasr with default parameters is likely to blow up the memory. In general blasr is not good at aligning almost identical long reads to reference, although there are some parameters to boost the run time for this use case (https://github.com/PacificBiosciences/blasr/wiki/To-align-long-and-almost-identical-sequences).

**Comment by alwaysrejoice** [comment]
Hi
thanks for your reply. But I still have some questions about blasr.
I do want to align homan genome with blasr using PacBio dataset, because I want to use this alignment result on PBHoney. 
I tried to run small piece file (the one I use is just 2.4M) to align human_genome.fasta, which is still 3G.
I ran it on my computer, which have 15G memory. I just used --nproc 1 with your recommendation parameters for long reads. 
But, the job still took over one day long and never finished and there was no output there. I checked the memory as well, my 15G memory, almost run out. Why it happens?  
Will the program output partial result during the program running?

**Comment by ylipacbio** [comment]
It's typical to see ~ 15 memory aligning to human reference because human reference sequence itself is 3.2G and its suffix array is ~12G. The alignment does not take much memory in this case. 

I would recommend to split input fasta files into chunks, and align each chunk to blasr with --nproc 10 (depending on available memory). These blasr jobs can be qsub-ed to cluster if you have distribute computing system (e.g., SGE).
The benefit is that (1) faster if you have a distribute computing system (2) reads in each chunk are processed independently so that even if some chunks crashed, you still get the rest and can restart the failed one. While with a big input, if anything crashes, you have to start over.

BLASR takes a long time and lots of memory to process long alignments. If input is big (~420G), the long alignments would eventually sink in memory (e.g., short alignments come and go, while long alignments stays in memory, thus in the end most alignments being processed are long alignments and take lots of memory.

**Comment by zhk2017** [comment]
use the latest version blasr will be fixed.
