### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by TakashiKoyama** [PacificBiosciences/blasr#343]
Hi,
I got error in compiling blasr as shown below.
Could anyone help me?
```
$ make
g++ -O3 -g -DSHA1_7=\"bed926d\" -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/koyama/Downloads/blasr/libcpp/alignment -I/home/koyama/Downloads/blasr/libcpp/hdf -I/home/koyama/Downloads/blasr/libcpp/pbdata   -c -o Blasr.o Blasr.cpp
Blasr.cpp: In function 'int main(int, char**)':
Blasr.cpp:1355:73: error: no matching function for call to 'ReaderAgglomerate::Initialize(bool, bool&)'
         initReturnValue = reader->Initialize(true, params.polymeraseMode);
                                                                         ^
Blasr.cpp:1355:73: note: candidates are:
In file included from iblasr/BlasrHeaders.h:71:0,
                 from iblasr/BlasrMiscs.hpp:4,
                 from Blasr.cpp:3:
/home/koyama/Downloads/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:89:9: note: int ReaderAgglomerate::Initialize(std::string&)
     int Initialize(string &pFileName);
         ^
/home/koyama/Downloads/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:89:9: note:   candidate expects 1 argument, 2 provided
/home/koyama/Downloads/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:95:9: note: int ReaderAgglomerate::Initialize(FileType&, std::string&)
     int Initialize(FileType &pFileType, string &pFileName);
         ^
/home/koyama/Downloads/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:95:9: note:   no known conversion for argument 1 from 'bool' to 'FileType&'
/home/koyama/Downloads/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:99:9: note: int ReaderAgglomerate::Initialize(bool)
     int Initialize(
         ^
/home/koyama/Downloads/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:99:9: note:   candidate expects 1 argument, 2 provided
make: *** [Blasr.o] Error 1
```

Thank you for your kind helps!!

**Comment by pb-cdunn** [comment]
This is related to the "nopbbam" flag.

Try a "cmake" build instead. That's what we are using now.

**Comment by benoistlaurent** [comment]
Hi, 

Same issue here using cmake.

Problem seems to be that RenderAgglomerate does not defines a Initialize function with prototype `Initialize(bool, bool)`.

**Comment by SRodenburg** [comment]
I am having the exact same error. Can't get it installed with either cmake or the regular installation. Is there any solution yet?

**Comment by SukyiR** [comment]
I have the same error with RednerAgglomerate when tried to compile normally.

However with cmake option, I get the following error with BOOST_INC:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/#/blasr/pbbam/src/Boost_INCLUDE_DIR
   used as include directory in directory /home/#/blasr/pbbam/src
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/#/blasr
   used as include directory in directory /home/#/blasr
   used as include directory in directory /home/#/blasr
   used as include directory in directory /home/#/blasr
   used as include directory in directory /home/#/blasr
   used as include directory in directory /home/#/blasr
   used as include directory in directory /home/#/blasr
   used as include directory in directory /home/#/blasr
   used as include directory in directory /home/#/blasr
   used as include directory in directory /home/#/blasr

-- Configuring incomplete, errors occurred!


I use the boost version 1.62.

I would like to know what's the issue here.

**Comment by TakashiKoyama** [comment]
Hi,

I could install blasr from pitchfork (https://github.com/PacificBiosciences/pitchfork).
It's quite easy. Try it!

**Comment by SRodenburg** [comment]
@TakashiKoyama Thanks for the tip!
I finally managed to install blasr very easily using pitchfork indeed.
```
git clone git://github.com/PacificBiosciences/pitchfork
cd pitchfork
make blasr 
```

After compiling, the binaries are in pitchfork/deployment/bin/. To run, the only remaining thing to do is to export the path variables:
`export LD_LIBRARY_PATH=$(pwd -P)/lib/:$(pwd -P)/include/`

**Comment by TakashiKoyama** [comment]
Great!!
Please be aware that, if LD_LIBRARY_PATH is set, yum become unavailable as I posted in https://github.com/PacificBiosciences/pitchfork/issues/390 .

@mhsieh gave me a valuable suggestion but, in my case, yum is finally available if I installed tools with HAVE_PYTHON variable in setting.mk even LD_LIBRARY_PATH is set.

**Comment by skoren** [comment]
I had the same build issue in the most recent code, both make and cmake. The issue is that the libcpp commit linked from blasr's repo is out of date. The ```Initialize(bool, bool)``` call was added in commit 95ae4787cc8cbb7cfa0f246942c134fa466bb565 on 3/3: https://github.com/PacificBiosciences/blasr_libcpp/commit/95ae4787cc8cbb7cfa0f246942c134fa466bb565 but the blasr repo points to commit https://github.com/PacificBiosciences/blasr_libcpp/commit/37074e07e0178705f7d545fd9a494aa2354392b9 from 1/31. The pointer in the blasr repo should be updated.
