### ISSUE TITLE
CIGAR string and MAPQ

### ISSUE THREAD

**Issue by esolares** [PacificBiosciences/blasr#57]
Hi,

I was trying to pull the MAPQ and CIGAR string for calculating percent identity, but realized that the MAPQ at times did not coincide with the quality of the alignment. I also noticed that the number of subsitutions are not put in the cigar string. Only M(matches),D(deletions) and I(insertions) and not = or X (possibly due to not being 1.4 sam format)

I ran BLASR on default with the exception of bestn 1 and sam out.

Do you recommend a way to calculate % identity? other than (M)/(M+I+D)

**Comment by mchaisso** [comment]
For now, you have to parse cigar strings to compute % identity.

**Comment by ylipacbio** [comment]
In the next release, blasr will support CIGAR strings in 1.4 SAM format (replace M with X and =, feature added but not released on github).

For now, you need to parse cigar strings with reference sequences in order to get %identity. 
You may also generate blasr alignments in other formats e.g., -m 4 or -m 5, which show %identity as a column. 
If you want to remove alignments of which percentage identity is less than p, you may use samFilter to do this.
